# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7bda08e8470a9b7025c0c835ad70275e162b72185d92b8cef1535b2059755626eb9d15a48fd198b2b79789dfd32202afd1e88c691b3d443f5bb294b7838e540

test:
  secret_key_base: 90d4d52f88ae84fcfc82180e0510a27de40573fe3a32e3a7ab6a098de5f7596c70ca117517544a32c8197c8f8f505038ce7e373fcdaac6d9e2a081db8332d303

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
